esphome:
  name: epaper8266

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret ssid 
  password: !secret password 
  domain: !secret domain 
  
#  manual_ip:
#    # Set this to the IP of the ESP
#    static_ip: 192.168.1.177
#    # Set this to the IP address of the router. Often ends with .1
#    gateway: 192.168.1.1
#    # The subnet of the network. 255.255.255.0 works for most home networks.
#    subnet: 255.255.255.0

captive_portal:

time:
  - platform: homeassistant
    id: ntp

# fonts directory and ttf file are required 
font:
  - file: "fonts/verdana.ttf"
    id: font1
    size: 36
    glyphs: |-
      !"%()+=,-_./:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz

spi:
  clk_pin: D5
  mosi_pin: D7

# Your sensor values of target Home Assistant 
sensor: 
  - platform: homeassistant 
    entity_id: sensor.2_5um
    id: indoor_pm25
    internal: true 
  - platform: homeassistant 
    entity_id: sensor.naver_weather_ultrafinedust_1
    id: outdoor_pm25
    internal: true 
  - platform: homeassistant 
    entity_id: sensor.mh_z19_co2_value
    id: co2
    internal: true 

    
display:
  - platform: waveshare_epaper
    cs_pin: D8
    dc_pin: D2
    busy_pin: D1
    reset_pin: D4
    model: 2.70in
    rotation: 270
    update_interval: 60s 
    lambda: |-
      // position 
      #define xRes 264
      #define yRes 176 
      #define pad 10
      
      it.strftime(0 + pad, 0 + pad, id(font1), "%m-%d %H:%M", id(ntp).now());
      it.printf(0 + pad, 0 + pad + 36, id(font1), TextAlign::TOP_LEFT, "0PM25: %.0f", id(outdoor_pm25).state);
      it.printf(0 + pad, 0 + pad + 36 * 2, id(font1), TextAlign::TOP_LEFT, "IPM25: %.0f", id(indoor_pm25).state);
      it.printf(0 + pad, 0 + pad + 36 * 3, id(font1), TextAlign::TOP_LEFT, "CO2: %.0f", id(co2).state);
      

 
